// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ShooterToggle.h"
#include "SmartDashboard/SmartDashboard.h"
ShooterToggle::ShooterToggle() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void ShooterToggle::Initialize() {
	if(Robot::shooter->motorsOn == false)
	{
		Robot::shooter->motorsOn = true;
	}
	else
	{
		Robot::shooter->motorsOn = false;
	}
}

// Called repeatedly when this Command is scheduled to run
void ShooterToggle::Execute() {
	if(Robot::shooter->motorsOn == false)
	{
		Robot::shooter->shooterMotorA->Set(0);
		Robot::shooter->shooterMotorB->Set(0);
	}
	else
	{
		Robot::shooter->shooterMotorA->Set(0.5);
		Robot::shooter->shooterMotorB->Set(0.5);
	}
	SmartDashboard::PutBoolean("on", Robot::shooter->motorsOn);
}

// Make this return true when this Command no longer needs to run execute()
bool ShooterToggle::IsFinished() {
	return true;
}

// Called once after isFinished returns true
void ShooterToggle::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShooterToggle::Interrupted() {

}
