// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
CANJaguar* RobotMap::intakeIntakeMotor = NULL;
CANJaguar* RobotMap::conveyorConveyorMotor = NULL;
CANJaguar* RobotMap::shooterShooterMotorA = NULL;
CANJaguar* RobotMap::shooterShooterMotorB = NULL;
CANJaguar* RobotMap::armArmMotorA = NULL;
CANJaguar* RobotMap::armArmMotorB = NULL;
CANJaguar* RobotMap::chassisfrontLeft = NULL;
CANJaguar* RobotMap::chassisfrontRight = NULL;
CANJaguar* RobotMap::chassisbackLeft = NULL;
CANJaguar* RobotMap::chassisbackRight = NULL;
DoubleSolenoid* RobotMap::spoilerpneSpoiler = NULL;
DoubleSolenoid* RobotMap::stopperpneStopper = NULL;
DoubleSolenoid* RobotMap::shifterpneShifter = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	intakeIntakeMotor = new CANJaguar(11);
	
	
	conveyorConveyorMotor = new CANJaguar(12);
	
	
	shooterShooterMotorA = new CANJaguar(7);
	
	
	shooterShooterMotorB = new CANJaguar(8);
	
	
	armArmMotorA = new CANJaguar(9);
	
	
	armArmMotorB = new CANJaguar(10);
	
	
	chassisfrontLeft = new CANJaguar(2);
	
	
	chassisfrontRight = new CANJaguar(4);
	
	
	chassisbackLeft = new CANJaguar(3);
	
	
	chassisbackRight = new CANJaguar(5);
	
	
	spoilerpneSpoiler = new DoubleSolenoid(0, 5, 2);      
	lw->AddActuator("Spoiler", "pneSpoiler", spoilerpneSpoiler);
	
	stopperpneStopper = new DoubleSolenoid(0, 6, 1);      
	lw->AddActuator("Stopper", "pneStopper", stopperpneStopper);
	
	shifterpneShifter = new DoubleSolenoid(0, 3, 4);      
	lw->AddActuator("Shifter", "pneShifter", shifterpneShifter);
	


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
